left_front_wheel:
  steering_link_name: frontwheellft
  steering_controller_name: left_steering_ctrlr
  axle_controller_name: left_front_axle_ctrlr
  diameter: 0.28

right_front_wheel:
  steering_link_name: frontwheelrgt
  steering_controller_name: right_steering_ctrlr
  axle_controller_name: right_front_axle_ctrlr
  diameter: 0.28

left_rear_wheel:
  link_name: backwheellft
  axle_controller_name: left_rear_axle_ctrlr
  diameter: 0.28

right_rear_wheel:
  link_name: backwheelrgt
  axle_controller_name: right_rear_axle_ctrlr
  diameter: 0.28

